### ISSUE TITLE
Bad design in REST method

### ISSUE THREAD

**Issue by amihaiemil** [teamed/requs#106]
Method [post(...)](https://github.com/teamed/requs/blob/master/requs-demo/src/main/java/org/requs/rest/InstantRs.java) currently returns a simple String on success and throws exception on failure. 

It should always return a Response object with appropriate status. Also, we can get rid of "NotNull" annotation and replace it with ``DefaultValue("")`` (maybe check for empty string and return a Response with 412 status?) 

Thus, on success it would 
```
    return Response.ok().entity(
             Json.createObjectBuilder()
                .add("spec", xml.nodes("/spec").get(0).toString())
                .add("html", xsl.applyTo(xml))
                .build().toString()
    ).build();
```

and on error it would 
```
    return Response.status(HttpURLConnection.HTTP_INTERNAL_ERROR)
                    .entity(ExceptionUtils.getStackTrace(ex))
                    .build();
```

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by amihaiemil** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@amihaiemil I don't see why returning a String is bad. JAX-RS recommends to do it this way. it's simpler.
